image: node:16-alpine

.releases:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|beta)/ && $CI_PIPELINE_SOURCE != 'schedule' && $CI_COMMIT_MESSAGE =~ /^(feat|fix).*/

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/ || $CI_COMMIT_TAG
      when: never
    - when: always

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store

before_script:
  - apk update --quiet
  - apk add --quiet zip curl git ack
  - curl -LSs https://unpkg.com/@pnpm/self-installer | node
  - pnpm config set store-dir .pnpm-store
  - pnpm set verify-store-integrity false
  - pnpm install --reporter=silent

stages:
  - test
  - build
  - release

jsonlint:
  stage: test
  script:
    - pnpm --silent exec jsonlint -q --enforce-double-quotes pt-BR
  rules:
    - if: $CI_PIPELINE_SOURCE != 'schedule'
      changes:
          - pt-BR/**/*.json

build:
  stage: build
  script:
    - export NEXT_VERSION=$(pnpm --silent exec semantic-release --dry-run | ack -io '(?<=The next release version is )(.*)(?=$)')
    - export NEXT_DOWNLOAD=$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$CI_PROJECT_NAME/$NEXT_VERSION/pt-BR.zip
    - pnpm --silent exec json -I -f pt-BR/module.json -e 'this.version="'$NEXT_VERSION'"' -e 'this.download="'$NEXT_DOWNLOAD'"'
    - pnpm --silent exec json -I -f package.json -e 'this.version="'$NEXT_VERSION'"'
    - zip -r -9 pt-BR.zip pt-BR -x "pt-BR/lang/en/*"
  artifacts:
    name: pt-BR
    when: on_success
    paths:
      - package.json
      - pt-BR.zip
      - pt-BR/module.json
  extends: .releases

publish:
  stage: release
  script:
    - pnpm --silent exec semantic-release
  dependencies:
    - build
  extends: .releases
