"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://fvtt.crowdin.com"

"preserve_hierarchy": false

"commit_message": "chore(crowdin): new translations %original_file_name% from Crowdin"
"append_commit_message": false

files:
  [
    {
      "source": "/pt-BR/lang/en/en.json",
      "translation": "/pt-BR/lang/%locale%/foundry.json",
      "update_option": "update_as_unapproved",
    },
  ]
